### PR TITLE
Namespace of Image is now configurable for ImageStream Trigger

### PR DESCRIPTION
**Pull request by retosbb**
Hello Donovan,

In our Case the Image of the Deployment is not in the Same Project in Openshift.
Therefore we must define the Namespace in which the Image can be found.

This is the change, i have added a additional property for the Deployment.

What do you think about this Change?

Regards,
Reto Zeller

### CODE REVIEW

**Comment by donovanmuller** [comment]
Thanks for the contribution Reto!

Apologies for the late reply, I was away for a few days.

Ironically, I might have already implemented something very similar to this on my local branch which I haven't pushed upstream yet 😃

Let me know once you're done with your commits and I'll check if there is any overlap between what we've both done (I will consider yours over mine if it is actually the same implementation, that way at least you didn't waste any time...)

**Comment by retosbb** [comment]
Hi Donovan,

Okay, i have problems with the IntegrationTests wich are run in this Travis CI. 
The Log in not completely displayed, so i can not find the error, and that made it a bit dificult. Local i can not run the Integration test.

I will make a new branch, only with the production Code changes(no test code changes).

I will inform you when i'm ready.

**Comment by retosbb** [comment]
This PR will be deleted. The PR is #34

**Comment by retosbb** [comment]
Hi Donovan,

there is something special.
When i add a logback.xml to you coder with the loggin-starter package from spring-boot in Maven, the test is sucess. Without that it fails.

Is this is a known behavior? Have you any idea why this happened.

Reto

**Comment by donovanmuller** [comment]
No idea 😕 I'll take a look and review #34 tomorrow...

**Pull request closed without merging**
